### ISSUE TITLE
Need to install fftw3-dev

### ISSUE THREAD

**Issue by svank** [ivanzmilic/me_inversion_exercises#1]
Hi Ivan,

When following the guide in python_install.dat, I had to install fftw3-dev rather than fftw3 for pyMilne to build. This is on Ubuntu 20.04.

**Comment by ivanzmilic** [comment]
Sounds reasonable, actually might have been the same with me. Going to
update that one now...

**Comment by svank** [comment]
Want to point out that python_install.dat now mentions fftw-dev. I don't know if that does work, but it's fftw**3**-dev that I installed and which seems to have worked just fine. Otherwise looks good!

**Comment by ivanzmilic** [comment]
Hey Sam

Interesting. I checked in the meantime and for me fftw3 (no -dev) is what
is installed. apt autocomplete offers fftw-dev but fftw3-dev also exists
and can be installed with apt. I will add all of these.

Thanks a lot!
